unix_users:
  - {
      name: "test_1",
      uid: 2000,
      state: "present",
      comment: "User 1",
      password: "{{ 'Tk6EaVDW' | password_hash('sha512') }}",
      public_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpColpr610FSEOVPCzSlPB2KrGdbMFKDUQBmNZ0Pc8cACiiTzHQ/RMXUS0B+eOnI33sGXbmOOlOwkPqoS3MVa0TYQWaUJo8XcuUctRm76TD8TYP/jpQDB2OvRXh0YUbKJrRMxF7VEGMDPqDLHqoZ6lQnZfwSXEbQTh4WTkQBXKqOEkhMVnZqdR15L42TIxwYfhS16idbe93qI62HIXImjjLMYBzWDSZDK7Tbfniua+iwRcKbxEPPHp6elJF2yhVpGs4lBPGmlO/h6h5GTFAQ4Z3KRtldNp1a6G37tyC2J+gtGMRoQBngvrw216HhJbETTtOkAc+/ieKFhZ+LV0ebG9 hoge@provisioning"
    }
  - {
      name: "test_2",
      uid: 2001,
      state: "present",
      comment: "User 2",
      password: "{{ 'T5wEAjKv' | password_hash('sha512') }}",
      public_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpColpr610FSEOVPCzSlPB2KrGdbMFKDUQBmNZ0Pc8cACiiTzHQ/RMXUS0B+eOnI33sGXbmOOlOwkPqoS3MVa0TYQWaUJo8XcuUctRm76TD8TYP/jpQDB2OvRXh0YUbKJrRMxF7VEGMDPqDLHqoZ6lQnZfwSXEbQTh4WTkQBXKqOEkhMVnZqdR15L42TIxwYfhS16idbe93qI62HIXImjjLMYBzWDSZDK7Tbfniua+iwRcKbxEPPHp6elJF2yhVpGs4lBPGmlO/h6h5GTFAQ4Z3KRtldNp1a6G37tyC2J+gtGMRoQBngvrw216HhJbETTtOkAc+/ieKFhZ+LV0ebG9 hoge@provisioning"
    }

kernel_parameter:
  - {
      name: "kernel_parameter_setting",
      net.ipv4.conf.all.arp_notify: 1,
      net.ipv6.conf.all.disable_ipv6: 1,
      net.ipv4.ip_forward: 0,
      net.ipv4.conf.default.rp_filter: 1,
      net.ipv4.conf.default.accept_source_route: 0,
      kernel.sysrq: 0,
      kernel.core_uses_pid: 1,
      net.ipv4.tcp_syncookies: 1,
      kernel.msgmnb: 65536,
      kernel.msgmax: 65536,
      kernel.shmmax: 68719476736,
      kernel.shmall: 4294967296,
      net.ipv4.tcp_keepalive_intvl: 75,
      net.ipv4.tcp_keepalive_probes: 3,
      kernel.threads-max: 90000,
      net.ipv4.tcp_keepalive_time: 60,
      net.core.somaxconn: 1024,
      net.ipv4.tcp_fin_timeout: 30,
      fs.file-max: 412328,
      vm.swappiness: 10,
    }