- hosts: sandbox
  become: yes
  become_user: root
  tasks:
  roles:
    - hostname
    - timezone
    - unix_users
    - httpd
    - {role: sudoers/test_1_allow, user_name: test_1}
    - cron/yum_autoupdate
    - samples/shell